language: python
python:
  - "3.6.4"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install: "pip3 install -r requirements.txt"
script:
- SECRET_KEY="thisagain" ./manage.py test
