language: python
python:
  - "3.6.4"
matrix:
  include:
    - python: 3.7.1
      sudo: true
install: "pip3 install -r requirements.txt"
after_install:
 - SECRET_KEY="thisagain" ./manage.py migrate
before_script:
 - SECRET_KEY="thisagain" ./manage.py runserver localhost:8000 &
script:
- SECRET_KEY="thisagain" ./manage.py test

dist: xenial
addons:
  chrome: stable
before_install:
 - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
