language: python
python:
  - "3.6.4"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install: "pip3 install -r requirements.txt"
script:
- SECRET_KEY="thisagain" ./manage.py test

dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
